name: "Tests"

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set up node
        uses: actions/setup-node@v3
        with: 
          node-version: 18
          cache: npm
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: module-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Tests e2e
        run: npm run test:e2e
        env:
          ENV_TEST: ${{ secrets.ENV_TEST }}